### ISSUE TITLE
Improper Size of transform_rounds

### ISSUE THREAD

**Issue by quantumburnz** [ivanmrsulja/keepass2john#1]
Hi,
I increased the value of hash iterations in my KeePass DB, and I wasn't able to crack a known hash. According to https://[gist.githubusercontent.com/msmuenchen/9318327/raw/f6cbc07c01297f129700b7e14e1013253ab8b44f/gistfile1.txt](https://gist.githubusercontent.com/msmuenchen/9318327/raw/f6cbc07c01297f129700b7e14e1013253ab8b44f/gistfile1.txt):
`5.7) bId=6: TRANSFORMROUNDS, LE QWORD.`

Therefore, I updated the following in the script from a DWORD to QWORD, and I'm getting the correct number of rounds now.
`transform_rounds = struct.unpack("Q", data[index:index+8])[0]`

**Comment by ivanmrsulja** [comment]
You are right, I don't believe how it worked for me in the past with a bug like this :smile: thank you for providing the fix as well!
